### PR TITLE
Avatar Component Added

### PR DESCRIPTION
**Pull request by Mahi24-prog**
Avatar Component Added, Please Review it.

### Link for Review:
https://avatarui.netlify.app/

### CODE REVIEW

**Review by MiheerTamkhane — APPROVED** [review]
Looks nice to me

**Review by narharikale — APPROVED** [review]

**Review by ZuberDunge — COMMENTED** [review]
Looks good to me

**Comment by t007rushi** [comment]
> Avatar Component Added, Please Review it.
> 
> ### Link for Review:
> https://avatarui.netlify.app/

Just add more description of variations like "added small to large size avatar"

**Review by sakleprajwal — COMMENTED** [review]
Looks good. Please go ahead

**Review by prathmeshjagtap — COMMENTED** [review]
Looks good code is well structure and clean

**Comment by vaibhav18matere** [comment]
looks clean , good to go

**Pull request merged**
