### PR TITLE
Navigation Component Added

### PR DESCRIPTION
**Pull request by Mahi24-prog**
Link For Review :
https://navigationui.netlify.app/component
Screenshot (5)
s

### CODE REVIEW

**Review by sakleprajwal — APPROVED** [review]
Code looks clean and readable. No changes required. Please go ahead.

**Review by ajit-sharmaGH — APPROVED** [review]
looks fine

**Comment by prath-dev** [comment]
clean and Elegant UI

**Review by harshkotkar5557 — COMMENTED** [review]
Very thing looks good.

**Pull request merged**
